name: unit-tests
on: [push]
jobs:
  build:
    run-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install libpng-dev libjpeg-dev libatlas-base-dev libblas-dev libgsl-dev clang
      - run: cd lib && ./configure --disable-openmp && make lib && cd ../bin && make && cd ../site && make source
  test:
    needs: build
    run-on: ubuntu-20.04
    steps:
      - run: cd ../test && make && make test
